### ISSUE TITLE
Dithering ficker with low level of strings

### ISSUE THREAD

**Issue by joaopmrod** [Yona-Appletree/LEDscape#50]
Why do I see a lot of flickering when I activate dithering with 8 string * 100 pixels and it becomes much better when I change it to 48 strings * 100 pixels?

**Comment by Yona-Appletree** [comment]
I'd have to do some testing, but it may simply be that dithering is getting disabled due to insufficient time when you're running 48x100. Some blinking is normal with dithering -- it's a trade off. If you're curious to debug it, take a look at `render_thread` in `opc-server.c`. Try tweaking `maxDitherFrames` and look at how `dithering_enabled` is setup. I'm happy to accept PRs that improve things... the dithering logic is far from perfect.
